/*
 * Copyright (C) 2017 OrionStar Technology Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * 以下为中文简体文本字符信息
 * 默认为简体中文，以下文字信息分为两类，分开存储
 * 第一类：需要在其他语音的js文件内同步添加（需翻译）。
 * 第二类：不需要适配国际化文字信息（无需翻译）
 */
export default {
    intoTtsArray: [
        '当当当，我又可以到处溜达啦',
        '给我一个路线，消毒小助手立刻上线'
    ],
    settings: '设置',
    opkChange: '应用切换',
    meal: '送餐',
    welcomeText: '揽客',
    leading: '领位',
    desk: '跑堂',
    plateRecycling: '回盘',
    toastSetTwoPlaceAtLeast: '请至少设置两个位置点',
    toastNoAdvertRes: '暂时没有广告资源',
    faceSensitivityName: ['低', '中', '高'],
    labelCruiseSpeed: '消毒速度配置',
    titleBaseSettings: '基础设置',
    titleAdvertSettings: '广告播放设置',
    titleAdvanceSettings: '消毒高级设置',
    labelSinglePicDuring: '单张图片展示时间',
    labelAutoGoNextStation: '自动去下一地点',
    suLabelAutoGoNextStation:
        '关闭开关，则需要手动切换点位，建议回收餐盘、发放自助餐使用',
    labelTtsPlayInterval: '文字播报间隔时间',
    labelStationStayTime: '点位停止时间',
    labelSearchPerson: '动态揽客',
    subLabelSearchPerson: '消毒过程看到人时，会跳转到揽客模式吸引顾客',
    labelFaceSensitivity: '识别灵敏度',
    labelCruiseRoute: '消毒路线配置',
    tipCruiseSpeedSet: '取值区间0.1~0.6m/s，建议速度0.4m/s',
    titleCruiseSpeedSet: '消毒速度配置(m/s)',
    toastCruiseSpeedOverOfRange: '速度超过取值范围',
    hintSinglePicDuring: '请输入单张图片展示时间',
    tipSinglePicDuring: '仅针对"文字播报+图片"类型的广告生效，取值区间10-300s',
    subTitleSinglePicDuring: '单张图片展示时间(s)',
    toastSinglePicDuringOverOfRange: '时间超过取值区间',
    hintTextPlayInterval: '请输入文字播报间隔时间',
    tipTextPlayInterval: '仅针对"文字播报+图片"类型的广告生效，取值区间1-300s',
    subTitleTextPlayInterval: '文字播报间隔时间(s)',
    toastTextPlayIntervalOverOfRange: '时间超过取值区间',
    hintStationStayTime: '请输入停止时间，取值区间0-3600s',
    tipStationStayTime: '点位停止时间',
    subTitleStationStayTime: '点位停止时间(s)',
    toastStationStayTimeOverOfRange: '时间超过取值区间',
    subLabelAutoGoNextStation:
        '关闭开关，则需要手动切换点位，建议回收餐盘、发放自助餐使用',
    titleCruiseMode: '消毒模式',
    ttsCheckEstimate: '请检查是否定位成功',
    toastWillGoPosition: '即将前往%s',
    toastGoPosition: '正在前往%s',
    toastGoNextPosition: '去下个地点',
    toastCruiseHasPaused: '消毒已暂停',
    buttonContinueCruise: '继续消毒',
    buttonCancelCruise: '结束任务',
    modeWelcome: '揽客模式',
    modeMeal: '送餐模式',
    modeAutoDesk: '跑堂模式',
    modeLeading: '领位模式',
    modePlate: '回盘模式',
    ttsAvoid: [
        '哎呀，你挡住我了，请不要站在我面前哦',
        '交通台提醒您，请记得给机器人让路哦',
        '请让我先过去吧',
        '请让一下吧',
        '麻烦请您让一下吧'
    ],
    deliveryAvoid: [
        '哎呀，我被挡住了，请帮忙给让条路呀',
        '不好意思，请您让一下，机器人来啦',
        '叮当叮当，机器人来啦',
        '亲亲，帮忙让一下呀，机器人来啦',
        '请您不要太迷恋我，人家忙着呢',
        '英俊潇洒的你，美丽迷人的你就让一下我啦',
        '小可爱，不要挡在我前面惹，人家还要干活啦',
        '让一让啦好不好嘛(ma4)，人家还要工作呢',
        '叮铃(ling1)叮铃(ling1)，机器人来咯，借过一下下',
        '帅气美丽的哥哥姐姐，请让一下下呀',
        '麻烦让一下下啦，人家要迟到啦',
        '哥哥姐姐让一下，等我下班再来找你玩吧',
        '客官，麻烦让一下惹，我要过去咯',
        '小哥哥小姐姐，帮忙让条路呀',
        '请让一让呀，宝宝有小情绪啦',
        '请让一让， 人家只是个路过的宝宝嘿嘿',
        '求求你让我过去吧，做个机器人太难了'
    ],
    ttsNavigationGlobalPathFailedPleaseEditMap:
        '目标点不可到达，请检查地图标注或把机器人推到可通行区域',
    ttsNavigationNotEstimate: '请先定位',
    ttsNavigationOutMap: '目标点不可到达，请擦除地图噪点或重新定位',
    ttsNavigationUnReachable:
        '我找不到路啦，请将我推到附近的定位标签下方重试吧',
    nav_waitTimeout_tts: '我在这里已经等了太久了，请您帮帮我吧',
    // eslint-disable-next-line @typescript-eslint/camelcase
    warningTitle_waitTimeout: '多机等待超时',
    // eslint-disable-next-line @typescript-eslint/camelcase
    warningHint_waitTimeout: '其他机器人长时间未让出通道',
    titleNavigationUnReachable: '找不到路啦',
    subTitleNavigationUnReachable: '请把我推到附近的定位标签下方重试吧',
    errorCode: '错误码: ',
    buttonRetry: '重试',
    ttsWheelStop:
        '机器人轮子已多次遇到问题。\n请检查轮子是否被杂物卡住或运送超载\n请您排除问题后，再点击“恢复工作”。',
    titleWheelStop: '机器人轮子已多次遇到问题',
    subTitleWheelStop:
        '请检查轮子是否被杂物卡住或运送超载\n请您排除问题后再点击“恢复工作”',
    buttonNoHandle: '暂不处理',
    buttonRecovery: '恢复工作',

    // todo
    titleStartCruise: '开始消毒',
    toastCruiseRoutePointsUnReachable:
        '当前消毒路线中部分点位无法到达，请到小程序中重新配置哦',
    toastCruiseNoRoute: '当前没有配置消毒路线，请先配置',
    ttsDelivery: '免费小食请自取',
    buttonCancel: '取消',
    tipTextInput: '请输入文字内容',
    toastTextInput: '请输入内容',
    buttonConfirm: '确定',
    titleCruiseRoute: '行驶路线',
    buttonClearRoute: '清空路线',
    buttonSelectRoute: '点击选择行驶点',
    titleCruiseRouteWillAdd: '待添加',
    toastPasswordError: '密码错误',
    titlePleaseInputPassword: '请输入密码',
    toastPasswordVerifyFailed: '密码校验失败',
    titlePleaseUseQrCodeGetRoute: '请用微信扫一扫，在小程序上配置路线',
    avoidText: '过不去啦',
    avoidSubText: '请给我让条路吧',
    nav_multiRobotError_tts: '多机调度出现异常，请尝试重启或联系售后人员',
    warningHint_multiRobotError: '请对此画面拍照并联系售后人员',
    warningTitle_multiRobotError: '多机调度出现异常',
    labelAdvertVolume: '消毒广告音量',
    warningTitlePathInvalid: '我没有找到巡线',
    warningSubTitlePathInvalid: '请绘制巡线并发布',
    warningTitleRobotOutOfPath: '我脱离巡线了',
    warningSubTitleRobotOutOfPath: '请把我推到巡线范围内',
    waringTitleTargetOutOfPath: '目的地不在巡线范围内',
    warningSubTitleTargetOutOfPath: '请检查巡线并重新发布',
    labelCruiseVersion: '消毒版本',
    demoModalTitle: '演示设置',
    demoModalTips:
        '温馨提示：定时消毒开启后，导航避障时屏幕仍会继续播放消毒广告资源',
    timeCruiseSwitch: '定时消毒',
    cruiseStartTime: '消毒开始时间',
    inSituSwitch: '原地播报',

    mainScreenTitle: '我可以帮您做这些事',
    subTitleMainScreen1: '动态揽客',
    subTitleMainScreen2: '小食分发',
    subTitleMainScreen3: '循环回盘',
    toastCruiseNoLocalRoute: '当前没有配置消毒路线，请先配置',
    incompleteLocalRoute: '消毒路线不完整，请到设置中进行修改',
    closeLocalCruiseRouteTips:
        '温馨提示：本地路线已停用，请前往机器人管理后台配置消毒路线',
    subLabelCruiseRoute: '可配置本地消毒路线',
    useLocalCruiseRoute: '使用本地消毒路线',
    clearRoute: '清除点位',
    configLocalCruiseRoute: '已选择点位',
    emptyCruiseRouteBtnTip: '请点击列表点位',
    selectCruisePos: '点击选择梯控点位',
    chargePoint: '回充点',
    chargePile: '充电桩',
    locationPoint: '定位点',
    elevatorCenterPoint: '电梯中心',
    elevatorGatePoint: '电梯口',
    meetingRoom: '会议室',
    cafeRoom: '咖啡厅',
    financeOffice: '财务室',
    bathroom: '卫生间',
    estimatedTime: '预计用时',
    hour: '小时',
    minute: '分钟',
    disinfecting: '消毒中',
    remainingTime: '剩余时间',
    progress: '进度',
    onDisinfecting: '正在消毒',
    gocharging: '去充电',
    fullyAutomaticStart: '全自动开始',
    startButtonIsDry: '加液后，点这里',
    startButtonDryCheck: '请稍等',
    atomization_gear: '雾化档位设置',
    heigh_speed: '高速雾化',
    long_endurance: '长续航雾化',

    useRoute: '使用中的路线',
    route: '路线',
    localRoute: '编辑路线',
    routeNull: '空',
    onStatusChecking: '正在检测',
    nextStart: '即将执行',
    goToCharge: '我要去充电了',
    dryToCharge: '消毒液用完了，我要去充电了',
    isCharging: '正在充电',
    disinfectantNull: '消毒液用完了',
    disinfectantNullMsg: '请立即补充消毒液，然后点击“完成”',
    buttonKnow: '知道了',
    buttonComplete: '完成',
    goCharging: '正在前往充电桩',
    noPlan: '没有更多计划',
    planComplete: '消毒计划已完成',
    later: '最近',
    num: '个',
    plan: '计划',
    todayPlanAllComplete: '今日消毒计划已全部完成',
    stopCharging: '结束充电',
    disinfectionPlan: '消毒计划设置',
    useDisinfectionPlan: '使用消毒计划',
    manage: '管理',
    add: '添加',
    delete: '删除',
    editPlan: '消毒计划编辑',
    starTime: '开始时间',
    endTime: '结束时间',
    xdRoute: '消毒路线',
    pleaseSelect: '请选择',
    fixedPointDisinfection: '定点消毒',
    fixedPointDisinfectionTip: '打开后，导航途中不进行消毒作业',
    close: '关闭',
    open: '打开(请设置点位停留时间)',
    FixedPointResidenceTime: '定点停留时间',
    disinfectionTip1: '设置建议（但不强制）',
    disinfectionTip2: '1、每个计划时段以2小时左右为宜',
    disinfectionTip3: '2、相邻的计划间隔至少4个小时，以便机器人有充足的电量',
    disinfectionTip4: '3、实际设置以您的需求为准',
    save: '保存',
    selectTimeTip: '请选择时间',
    routeTip: '请选择路线',
    stopChargingTts: '请先站在我的侧面，然后点击结束充电',
    everyday: '每天',
    inputTip: '请输入定点停留时间，取值范围0~3600s',
    inputError: '请输入0~3600之间的时间',
    starTimeIllegal: '开始时间必须小于结束时间',
    endTimeIllegal: '结束时间必须大于开始时间',
    timeConflict: '与其他计划时段冲突，请检查后再设置',
    remaining: '剩余',
    chargingTts: '我正在充电呢，请稍后找我吧',
    stopChargingToast: '正在结束充电，请稍后...',
    noScheduleTaskWorking: '当前不在消毒计划内',
    gearModalList: ['高速雾化', '长续航雾化'],
    fullGearModalList: ['高速雾化', '长续航雾化', '极速模式'],

    stopChargingCountTts: '正在结束充电，请勿站在机器人前方',
    startChargingTts: '我要回去充电啦，请让让路',
    getOutElevatorTts: '我要出电梯了，好心的人类呀，给我让让路吧',
    enterElevatorTts: '我要进电梯了，麻烦您往旁边靠靠，把中间的位置留给我吧',
    warningSubtitleNavElevatorMapRong: '当前地图未做楼层设置，请修改后重试',
    arriveElevatorCenterTurnTts: '我要转身了，请您注意下哦，很高兴与您一起乘坐电梯'

};
